[package]
name = "scripty_stt_service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# add debug info to the release build
[profile.release]
incremental = false
codegen-units = 1
debug = true

[workspace]
members = [
  "stts_connection_handler",
  "stts_speech_to_text",
]
exclude = [
  "stt_testing",
]

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
stts_speech_to_text = { path = "stts_speech_to_text" }
stts_connection_handler = { path = "stts_connection_handler" }
