[package]
name = "stts_speech_to_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10"
tracing = "0.1"
once_cell = "1"
tokio = { version = "1", features = ["full"] }
whisper-rs = { version = "0.5.0", features = ["simd"] }
