[package]
name = "stts_speech_to_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
once_cell = "1"
tokio = { version = "1", features = ["full"] }
whisper-rs = { git = "https://github.com/tazz4843/whisper-rs", branch = "cuda-and-opencl-support", features = ["simd"] }
