[package]
name = "stts_speech_to_text"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.10"
dashmap = "5"
tracing = "0.1"
once_cell = "1"
coqui-stt = { git = "https://github.com/scripty-bot/coqui-stt" }